version: 2
jobs:
  build:
    macos:
      xcode: "9.0"

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      # - run:
      #     name: Install Pods
      #     command: pod install
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.cocoapods
            - Pods

  deploy:
    macos:
      xcode: "9.0"

    steps:
      - checkout

      - run:
          name: Deploy Podspec
          command: pod trunk push

workflows:
  version: 2
  build:
    jobs:
      - build
      - allow_deploy:
          type: approval

      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - allow_deploy
